config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'
  get '/search' => 'search#search'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  resources :users, only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create,:destroy]
    get :followings, on: :member
    get :followers, on: :member
    # resources :rooms, only: [:create] do
    #   resources :chats, only: [:create, :show]
    # end
  end
  
  resources :books do
    resource :favorites, only: [:create,:destroy]
    resources :book_comments, only: [:create,:destroy]
  end
  
  resources :chats, only: [:create, :show], param: :room_id
  resources :rooms, only: [:create]
  # get 'chats/create' => 'chats#create'
  # get 'chats/' => 'chats#show'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following
  
  has_many :chats, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  
  attachment :profile_image, destroy: false

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50}
  
  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end
  
  def self.search(how,content)
    if how == 'match'
      User.where("name LIKE?", "#{content}")
    elsif how == 'forward'
      User.where("name LIKE?", "#{content}%")
    elsif how == 'backward'
      User.where("name LIKE?", "%#{content}")
    elsif how == 'partial'
      User.where("name LIKE?", "%#{content}%")
    end
  end
  
  include JpPrefecture
  jp_prefecture :prefecture_code
  
  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end
  
  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  # skip_before_action :authenticate_user!, only: [:create]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
   def create
      @user = User.new(user_params)
      if @user.save
        ThanksMailer.send_confirm_to_user(@user).deliver
        sign_up(resource_name, resource)
        redirect_to @user
      else
        render 'new'
      end
   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  private
  def user_params
    params.require(:user).permit(:email, :name, :postal_code, :prefecture_code, :city, :street, :password, :password_confirmation)
  end
  
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]
  # skip_before_action :authenticate_user!, only: [:show]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @currentUserUserRoom = UserRoom.where(user_id: current_user.id)
    @userUserRoom = UserRoom.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserUserRoom.each do |cu|
        @userUserRoom.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @userRoom = UserRoom.new
      end
    end
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def followings
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>

	<tr>
		<th>follows</th>
		<th>
			<%= link_to followings_user_path(user) do %>
				<%= user.followings.count %>
			<% end %>
		</th>
	</tr>

	<tr>
		<th>followers</th>
		<th>
			<%= link_to followers_user_path(user) do %>
				<%= user.followers.count %>
			<% end %>
		</th>
	</tr>
</table>

<% if user == current_user %>
	<div class="row">
		<%= link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
	</div>
<% else %>
	<% if user.followed_by?(current_user) %>
		<%= link_to "フォロー外す", user_relationships_path(user.id), class: "btn btn-primary", method: :delete %>
	<% else %>
		<%= link_to "フォローする", user_relationships_path(user.id), class: "btn btn-success", method: :post %>
	<% end %>
<% end %>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_with model:@user, local: true do |f| %>

	<!-- エラーメッセージ表示-->
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
			<ul>
				<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<!-- エラーメッセージ表示-->

	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name, class: "name" %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :profile_image, class: "user_image" %>
	</div>

	<div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/followers.html.erb
<h2>Follower Users</h2>
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
			<th></th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			<td><%= user.name %></td>
			<td>フォロー数：<%= user.followings.count %></td>
			<td>フォロワー数：<%= user.followers.count %></td>
			<td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/users/followings.html.erb
<h2>Following Users</h2>
<table class="table">
		<thead>
			<tr>
				<th>image</th>
				<th>name</th>
				<th colspan="3"></th>
				<th></th>
				<th></th>
			</tr>
		</thead>

		<tbody>
			<% @users.each do |user| %>
			<tr>
				<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
				<td><%= user.name %></td>
				<td>フォロー数：<%= user.followings.count %></td>
				<td>フォロワー数：<%= user.followers.count %></td>
				<td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
			</tr>
			<% end %>
		</tbody>
	</table>

app/views/users/index.html.erb
<%= render 'layouts/search' %>
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/form', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Users</h2>
		<!--users一覧 -->
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="3"></th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
					<td><%= user.name %></td>
					<td>フォロー数：<%= user.followings.count %></td>
					<td>フォロワー数：<%= user.followers.count %></td>
					<td>
						<% if current_user != user %>
							<% if user.followed_by?(current_user) %>
								<%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
							<% else %>
								<%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
							<% end %>
						<% end %>
					</td>
					<td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--users一覧 -->
	</div>
</div>

app/views/users/show.html.erb
<%= render 'layouts/search' %>
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>
		<% if @isRoom == true %>
			<p class="btn btn-default"><%= link_to "チャットへ", chat_path(@roomId, user_id: @user.id) %></p>
		<% elsif @user != current_user %>
			<%= form_with(model:@room, url: rooms_path, local: true) do |f| %>
				<%= f.fields_for :userRoom do |ur| %>
					<%= ur.hidden_field :user_id, value: @user.id %>
				<% end %>
				<%= f.submit "チャットを始める", class:"btn btn-default user-show-chat" %>
			<% end %>
		<% end %>

		<h2>New book</h2>
		<%= render 'books/form', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
					<th></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to user_path(book.user) do %>
								<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
							<% end %>
						</td>
						<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>
						<td>
							<% if book.favorited_by?(current_user) %>
								<%= link_to book_favorites_path(book), method: :delete do %>
									<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
									<%= book.favorites.count %>
								<% end %>
							<% else %>
								<%= link_to book_favorites_path(book), method: :post do %>
									<li class="fa fa-heart-o" aria-hidden="true"></li>
									<%= book.favorites.count %>
								<% end %>
							<% end %>
						</td>
						<td>コメント数：<%= book.book_comments.count %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
		<!--books一覧 -->
	</div>
</div>